export const servicesList = [
  {
    id: '1',
    title: 'АЭРОЙОГА',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et',
    url: '/img/аэройога.png',
    isHover: false,
  },
  {
    id: '2',
    title: 'ХАТХА-ЙОГА',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et',
    url: '/img/хатха-йога.png',
    isHover: true,

  },
  {
    id: '3',
    title: 'ДЕТСКАЯ ЙОГА',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et',
    url: '/img/хатха-йога.png',
    isHover: false,
    isDesc: false,
  },
  {
    id: '4',
    title: 'СТРЕТЧИНГ',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et',
    url: '/img/стретчинг.png',
    isHover: false,
  },
  {
    id: '5',
    title: 'СИЛОВОЙ ФИТНЕС',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et',
    url: '/img/силовой_фитнес.png',
    isHover: false,
  },
  {
    id: '6',
    title: 'ТАНЦЕВАЛЬНЫЙ ФИТНЕС',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et',
    url: '/img/силовой_фитнес.png',
    isHover: false,
  },
  {
    id: '7',
    title: 'ОЗДОРОВИТЕЛЬНЫЕ ПРАКТИКИ',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et',
    url: '/img/оздоровительная_практика.png',
    isHover: false,
  },
  {
    id: '8',
    title: 'МЕНТАЛЬНАЯ ПОМОЩЬ',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et',
    url: '/img/ментальная_помощь.png',
    isHover: false,
  },
  {
    id: '9',
    title: 'АРЕНДА ЗАЛА',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et',
    url: '/img/аренда_зала.png',
    isHover: false,
  },
  {
    id: '10',
    title: 'ПРОВЕДЕНИЕ ДНЕЙ РОЖДЕНИЙ',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et',
    url: '/img/дни_рождения.png',
    isHover: false,
  },
]